#TO MAKE MULTIPLE MULTICOMMANDS FOLLOW TEMPLATE BELOW REPLACE THE NUMBER AT THE END AT AN INCREMENT OF 1
MultiCommand0:
   #NAMES ARE TO BE LOWER CASED
   cmdName: "help"
   #TOO ADD A DELAY TO THE EXECUTOR DO AS FOLLOWS - "DELAY (MILISECONDS)"
   cmd:
   - "DELAY 1000"
   #COMMANDS ARE TO BE WITHOUT '/'
   - "help"
   - "DELAY 5000"
   - "help"